# Generated by Django 4.0.5 on 2022-06-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=6)),
                ('death', models.BooleanField(default=False)),
                ('kills', models.IntegerField()),
                ('description', models.TextField()),
                ('hp', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
